version: '3'
services:
  nginx:
    image: openresty/openresty
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./privkey.pem:/etc/nginx/privkey.pem"
      - "./fullchain.pem:/etc/nginx/fullchain.pem"
